defaultBaseImage: docker.io/golang:1.20

builds:
  - id: bom
    dir: .
    main: ./cmd/bom
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -extldflags "-static"
      - "{{ .Env.BOM_LDFLAGS }}"
