name: github pages
permissions:
  contents: write
on:
  push:
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v2.5.0
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: cd docs && npm install && hugo --minify

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@920cbb300dcd3f0568dbc42700c61e2fd9e6139c # v4.6.4
        with:
          folder: ./docs/public # The folder the action should deploy.
