name: Snapshot

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions: {}

jobs:
  snapshot:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check out code onto GOPATH
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Extract version of Go to use
        run: echo "GOVERSION=$(awk -F'[:@]' '/FROM golang/{print $2; exit}' Dockerfile.dev)" >> $GITHUB_ENV

      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: '${{ env.GOVERSION }}'
          check-latest: true
          cache: false

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
        with:
          install-only: true

      - name: Run Mage
        uses: magefile/mage-action@6a5dcb5fe61f43d7c08a98bc3cf9bc63c308c08e # v3.0.0
        with:
          version: latest
          args: buildBinariesSnapshot

      - name: check binary
        run: |
          ./dist/bom_linux_amd64_v1/bom version
          cat ./dist/bom.json.spdx
