name: Validate SPDX Conformance

on:
  pull_request:
    branches:
      - 'main'

permissions: {}

jobs:
  check-spdx:
    name: Check SPDX SBOMs
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v3.3.0
        with:
          go-version: '1.25'
          check-latest: true
          cache: false

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: |
          go run ./cmd/bom/main.go generate -i registry.k8s.io/pause > example-image-pause.spdx
          go run ./cmd/bom/main.go generate --format=json -i registry.k8s.io/pause > example-image-pause.spdx.json

      - uses: chainguard-dev/actions/setup-spdx@d886686603afb809f7ef9b734b333e20b7ce5cda
        with:
          spdx-tools-version: 1.1.8

      - uses: chainguard-dev/actions/setup-spdx@d886686603afb809f7ef9b734b333e20b7ce5cda
        with:
          download: false
          spdx-tools-version: 1.1.8
          sbom-path: example-image-pause.spdx

      - uses: chainguard-dev/actions/setup-spdx@d886686603afb809f7ef9b734b333e20b7ce5cda
        with:
          download: false
          spdx-tools-version: 1.1.8
          sbom-path: example-image-pause.spdx.json

      - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b  # v4.5.0
        if: ${{ always() }}
        with:
          name: Example SBOMs
          path: |
            example-image-pause.spdx
            example-image-pause.spdx.json
